def zamen(st):

    st = st.replace('|*','<span class="splice">')
    st = st.replace('|&', '<span class="var">')
    st = st.replace('|@', '<span class="mut">')
    st = st.replace('|(', '<span class="exon">')
    # st = st.replace('*|', '</span class="splice">')
    # st = st.replace('&|', '</span class="var">')
    # st = st.replace('@|', '</span class="mut">')
    # st = st.replace(')|', '</span class="exon">')
    st = st.replace('*|', '</span>')
    st = st.replace('&|', '</span>')
    st = st.replace('@|', '</span>')
    st = st.replace(')|', '</span>')
    # st = st.replace('gt', '<span class="sites">gt</span class="sites">')
    # st = st.replace('Gt', '<span class="sites">Gt</span class="sites">')
    # st = st.replace('gT', '<span class="sites">gT</span class="sites">')
    # st = st.replace('GT', '<span class="sites">GT</span class="sites">')
    # st = st.replace('ag', '<span class="sites">ag</span class="sites">')
    # st = st.replace('Ag', '<span class="sites">Ag</span class="sites">')
    # st = st.replace('aG', '<span class="sites">aG</span class="sites">')
    # st = st.replace('AG', '<span class="sites">AG</span class="sites">')
    return st
zag_f = open('zag_html.html','r')
name_file ='pax6_spl_alt.txt'
gen = open(name_file,'r')
file_out = open(name_file.replace('.txt','.html'),'w')
zag = zag_f.read()
zag = zag.replace('NAME',name_file)
file_out.write(zag)
for st in gen:
    file_out.write('<p> '+zamen(st)+'</p>')
file_out.write('\n\t</body>\n')
file_out.write('</html>')
gen.close()
file_out.close()
zag_f.close()